# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui-colorWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_colorWindow(object):
    def setupUi(self, colorWindow):
        colorWindow.setObjectName("colorWindow")
        colorWindow.resize(775, 608)
        self.centralwidget = QtWidgets.QWidget(colorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(200, 10, 551, 511))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 40, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 140, 61, 16))
        self.label_3.setObjectName("label_3")
        self.spinBoxContrast = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBoxContrast.setGeometry(QtCore.QRect(60, 60, 62, 22))
        self.spinBoxContrast.setMinimum(-1.0)
        self.spinBoxContrast.setMaximum(2.0)
        self.spinBoxContrast.setSingleStep(0.05)
        self.spinBoxContrast.setObjectName("spinBoxContrast")
        self.spinBoxLuminosite = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBoxLuminosite.setGeometry(QtCore.QRect(60, 110, 62, 22))
        self.spinBoxLuminosite.setMinimum(-1.0)
        self.spinBoxLuminosite.setMaximum(1.0)
        self.spinBoxLuminosite.setSingleStep(0.05)
        self.spinBoxLuminosite.setObjectName("spinBoxLuminosite")
        self.spinBoxSaturation = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBoxSaturation.setGeometry(QtCore.QRect(60, 160, 62, 22))
        self.spinBoxSaturation.setMinimum(-1.0)
        self.spinBoxSaturation.setMaximum(1.0)
        self.spinBoxSaturation.setSingleStep(0.05)
        self.spinBoxSaturation.setObjectName("spinBoxSaturation")
        self.spinBoxRed = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxRed.setGeometry(QtCore.QRect(60, 290, 61, 22))
        self.spinBoxRed.setMinimum(-100)
        self.spinBoxRed.setMaximum(100)
        self.spinBoxRed.setSingleStep(5)
        self.spinBoxRed.setObjectName("spinBoxRed")
        self.spinBoxGreen = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxGreen.setGeometry(QtCore.QRect(60, 350, 61, 22))
        self.spinBoxGreen.setMinimum(-100)
        self.spinBoxGreen.setMaximum(100)
        self.spinBoxGreen.setSingleStep(5)
        self.spinBoxGreen.setObjectName("spinBoxGreen")
        self.spinBoxBlue = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxBlue.setGeometry(QtCore.QRect(60, 410, 61, 22))
        self.spinBoxBlue.setMinimum(-100)
        self.spinBoxBlue.setMaximum(100)
        self.spinBoxBlue.setSingleStep(5)
        self.spinBoxBlue.setObjectName("spinBoxBlue")
        self.spinBoxNettete = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBoxNettete.setGeometry(QtCore.QRect(60, 220, 62, 22))
        self.spinBoxNettete.setMinimum(-1.0)
        self.spinBoxNettete.setMaximum(1.0)
        self.spinBoxNettete.setSingleStep(0.05)
        self.spinBoxNettete.setObjectName("spinBoxNettete")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 200, 47, 13))
        self.label_4.setObjectName("label_4")
        self.checkBoxMinMax = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxMinMax.setGeometry(QtCore.QRect(60, 480, 70, 17))
        self.checkBoxMinMax.setObjectName("checkBoxMinMax")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 270, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 330, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 390, 47, 13))
        self.label_7.setObjectName("label_7")
        self.buttonBoxDone = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBoxDone.setGeometry(QtCore.QRect(500, 540, 251, 23))
        self.buttonBoxDone.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBoxDone.setObjectName("buttonBoxDone")
        self.buttonBoxReset = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBoxReset.setGeometry(QtCore.QRect(50, 530, 81, 23))
        self.buttonBoxReset.setStandardButtons(QtWidgets.QDialogButtonBox.Reset)
        self.buttonBoxReset.setObjectName("buttonBoxReset")
        colorWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(colorWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 775, 21))
        self.menubar.setObjectName("menubar")
        colorWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(colorWindow)
        self.statusbar.setObjectName("statusbar")
        colorWindow.setStatusBar(self.statusbar)

        self.retranslateUi(colorWindow)
        QtCore.QMetaObject.connectSlotsByName(colorWindow)

    def retranslateUi(self, colorWindow):
        _translate = QtCore.QCoreApplication.translate
        colorWindow.setWindowTitle(_translate("colorWindow", "Rehaussement des couleurs"))
        self.label.setText(_translate("colorWindow", "Constraste"))
        self.label_2.setText(_translate("colorWindow", "Luminosité"))
        self.label_3.setText(_translate("colorWindow", "Saturation"))
        self.label_4.setText(_translate("colorWindow", "Netteté"))
        self.checkBoxMinMax.setText(_translate("colorWindow", "Min/Max"))
        self.label_5.setText(_translate("colorWindow", "Rouge"))
        self.label_6.setText(_translate("colorWindow", "Vert"))
        self.label_7.setText(_translate("colorWindow", "Bleu"))

class colorWindow(QtWidgets.QMainWindow): 

    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.ui = Ui_colorWindow()
        self.ui.setupUi(self)