# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui-optionWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
import os

class Ui_optionWindow(object):
    def setupUi(self, optionWindow):
        optionWindow.setObjectName("optionWindow")
        optionWindow.resize(437, 462)
        self.label_5 = QtWidgets.QLabel(optionWindow)
        self.label_5.setGeometry(QtCore.QRect(70, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(optionWindow)
        self.label_6.setGeometry(QtCore.QRect(270, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.groupBoxRed = dropedit(optionWindow)
        self.groupBoxRed.setGeometry(QtCore.QRect(10, 30, 201, 221))
        self.groupBoxRed.setTitle("")
        self.groupBoxRed.setObjectName("groupBoxRed")
        self.importLineRed = QtWidgets.QLineEdit(self.groupBoxRed)
        self.importLineRed.setGeometry(QtCore.QRect(10, 20, 161, 20))
        self.importLineRed.setObjectName("importLineRed")
        self.importLineRed.setText("")
        self.importLineRed.setReadOnly(True)
        self.importToolRed = QtWidgets.QToolButton(self.groupBoxRed)
        self.importToolRed.setGeometry(QtCore.QRect(170, 20, 25, 19))
        self.importToolRed.setObjectName("importToolRed")
        self.boxOrientationRouge = QtWidgets.QComboBox(self.groupBoxRed)
        self.boxOrientationRouge.setGeometry(QtCore.QRect(90, 60, 101, 22))
        self.boxOrientationRouge.setObjectName("boxOrientationRouge")
        self.boxOrientationRouge.addItem("")
        self.boxOrientationRouge.addItem("")
        self.boxOrientationRouge.addItem("")
        self.boxOrientationRouge.addItem("")
        self.boxOrientationRouge.setEnabled(False)
        self.label = QtWidgets.QLabel(self.groupBoxRed)
        self.label.setGeometry(QtCore.QRect(10, 60, 61, 20))
        self.label.setObjectName("label")
        self.label.setEnabled(False)
        self.label_2 = QtWidgets.QLabel(self.groupBoxRed)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_2.setEnabled(False)
        self.boxMiroirRouge = QtWidgets.QComboBox(self.groupBoxRed)
        self.boxMiroirRouge.setGeometry(QtCore.QRect(90, 100, 101, 22))
        self.boxMiroirRouge.setObjectName("boxMiroirRouge")
        self.boxMiroirRouge.addItem("")
        self.boxMiroirRouge.addItem("")
        self.boxMiroirRouge.addItem("")
        self.boxMiroirRouge.setEnabled(False)
        self.leftRed = QtWidgets.QToolButton(self.groupBoxRed)
        self.leftRed.setGeometry(QtCore.QRect(40, 160, 21, 21))
        self.leftRed.setArrowType(QtCore.Qt.LeftArrow)
        self.leftRed.setObjectName("leftRed")
        self.leftRed.setEnabled(False)
        self.downRed = QtWidgets.QToolButton(self.groupBoxRed)
        self.downRed.setGeometry(QtCore.QRect(60, 180, 21, 21))
        self.downRed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.downRed.setArrowType(QtCore.Qt.DownArrow)
        self.downRed.setObjectName("downRed")
        self.downRed.setEnabled(False)
        self.upRed = QtWidgets.QToolButton(self.groupBoxRed)
        self.upRed.setGeometry(QtCore.QRect(60, 140, 21, 21))
        self.upRed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.upRed.setArrowType(QtCore.Qt.UpArrow)
        self.upRed.setObjectName("upRed")
        self.upRed.setEnabled(False)
        self.rightRed = QtWidgets.QToolButton(self.groupBoxRed)
        self.rightRed.setGeometry(QtCore.QRect(80, 160, 21, 21))
        self.rightRed.setArrowType(QtCore.Qt.RightArrow)
        self.rightRed.setObjectName("rightRed")
        self.rightRed.setEnabled(False)
        self.origineRed = QtWidgets.QPushButton(self.groupBoxRed)
        self.origineRed.setGeometry(QtCore.QRect(120, 160, 43, 21))
        self.origineRed.setObjectName("origineRed")
        self.origineRed.setEnabled(False)
        self.groupBoxCyan = dropedit(optionWindow)
        self.groupBoxCyan.setGeometry(QtCore.QRect(220, 30, 201, 221))
        self.groupBoxCyan.setTitle("")
        self.groupBoxCyan.setObjectName("groupBoxCyan")
        self.importLineCyan = QtWidgets.QLineEdit(self.groupBoxCyan)
        self.importLineCyan.setGeometry(QtCore.QRect(10, 20, 161, 20))
        self.importLineCyan.setObjectName("importLineCyan")
        self.importLineCyan.setText("")
        self.importLineCyan.setReadOnly(True)
        self.importToolCyan = QtWidgets.QToolButton(self.groupBoxCyan)
        self.importToolCyan.setGeometry(QtCore.QRect(170, 20, 25, 19))
        self.importToolCyan.setObjectName("importToolCyan")
        self.label_4 = QtWidgets.QLabel(self.groupBoxCyan)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_4.setEnabled(False)
        self.rightCyan = QtWidgets.QToolButton(self.groupBoxCyan)
        self.rightCyan.setGeometry(QtCore.QRect(80, 160, 21, 21))
        self.rightCyan.setArrowType(QtCore.Qt.RightArrow)
        self.rightCyan.setObjectName("rightCyan")
        self.rightCyan.setEnabled(False)
        self.label_3 = QtWidgets.QLabel(self.groupBoxCyan)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 61, 20))
        self.label_3.setObjectName("label_3")
        self.label_3.setEnabled(False)
        self.upCyan = QtWidgets.QToolButton(self.groupBoxCyan)
        self.upCyan.setGeometry(QtCore.QRect(60, 140, 21, 21))
        self.upCyan.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.upCyan.setArrowType(QtCore.Qt.UpArrow)
        self.upCyan.setObjectName("upCyan")
        self.upCyan.setEnabled(False)
        self.leftCyan = QtWidgets.QToolButton(self.groupBoxCyan)
        self.leftCyan.setGeometry(QtCore.QRect(40, 160, 21, 21))
        self.leftCyan.setArrowType(QtCore.Qt.LeftArrow)
        self.leftCyan.setObjectName("leftCyan")
        self.leftCyan.setEnabled(False)
        self.boxMiroirCyan = QtWidgets.QComboBox(self.groupBoxCyan)
        self.boxMiroirCyan.setGeometry(QtCore.QRect(90, 100, 101, 22))
        self.boxMiroirCyan.setObjectName("boxMiroirCyan")
        self.boxMiroirCyan.addItem("")
        self.boxMiroirCyan.addItem("")
        self.boxMiroirCyan.addItem("")
        self.boxMiroirCyan.setEnabled(False)
        self.downCyan = QtWidgets.QToolButton(self.groupBoxCyan)
        self.downCyan.setGeometry(QtCore.QRect(60, 180, 21, 21))
        self.downCyan.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.downCyan.setArrowType(QtCore.Qt.DownArrow)
        self.downCyan.setObjectName("downCyan")
        self.downCyan.setEnabled(False)
        self.boxOrientationCyan = QtWidgets.QComboBox(self.groupBoxCyan)
        self.boxOrientationCyan.setGeometry(QtCore.QRect(90, 60, 101, 22))
        self.boxOrientationCyan.setObjectName("boxOrientationCyan")
        self.boxOrientationCyan.addItem("")
        self.boxOrientationCyan.addItem("")
        self.boxOrientationCyan.addItem("")
        self.boxOrientationCyan.addItem("")
        self.boxOrientationCyan.setEnabled(False)
        self.origineCyan = QtWidgets.QPushButton(self.groupBoxCyan)
        self.origineCyan.setGeometry(QtCore.QRect(120, 160, 43, 21))
        self.origineCyan.setObjectName("origineCyan")
        self.origineCyan.setEnabled(False)
        self.groupBoxActivate = QtWidgets.QGroupBox(optionWindow)
        self.groupBoxActivate.setGeometry(QtCore.QRect(10, 280, 411, 161))
        self.groupBoxActivate.setTitle("")
        self.groupBoxActivate.setObjectName("groupBoxActivate")
        self.groupBoxActivate.setEnabled(False)
        self.boxSuper = QtWidgets.QCheckBox(self.groupBoxActivate)
        self.boxSuper.setGeometry(QtCore.QRect(50, 60, 101, 31))
        self.boxSuper.setObjectName("boxSuper")
        self.groupBoxSuper = QtWidgets.QGroupBox(self.groupBoxActivate)
        self.groupBoxSuper.setEnabled(False)
        self.groupBoxSuper.setGeometry(QtCore.QRect(120, 9, 261, 142))
        self.groupBoxSuper.setTitle("")
        self.groupBoxSuper.setObjectName("groupBoxSuper")
        self.radioCouleur = QtWidgets.QRadioButton(self.groupBoxSuper)
        self.radioCouleur.setGeometry(QtCore.QRect(20, 25, 82, 17))
        self.radioCouleur.setObjectName("radioCouleur")
        self.radioNoirBlanc = QtWidgets.QRadioButton(self.groupBoxSuper)
        self.radioNoirBlanc.setGeometry(QtCore.QRect(20, 5, 82, 17))
        self.radioNoirBlanc.setChecked(True)
        self.radioNoirBlanc.setObjectName("radioNoirBlanc")
        self.saveSuper = QtWidgets.QPushButton(self.groupBoxSuper)
        self.saveSuper.setGeometry(QtCore.QRect(150, 15, 75, 23))
        self.saveSuper.setObjectName("saveSuper")
        self.origineSuper = QtWidgets.QPushButton(self.groupBoxSuper)
        self.origineSuper.setGeometry(QtCore.QRect(160, 80, 43, 21))
        self.origineSuper.setObjectName("origineSuper")
        self.leftSuper = QtWidgets.QToolButton(self.groupBoxSuper)
        self.leftSuper.setGeometry(QtCore.QRect(80, 80, 21, 21))
        self.leftSuper.setArrowType(QtCore.Qt.LeftArrow)
        self.leftSuper.setObjectName("leftSuper")
        self.upSuper = QtWidgets.QToolButton(self.groupBoxSuper)
        self.upSuper.setGeometry(QtCore.QRect(100, 60, 21, 21))
        self.upSuper.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.upSuper.setArrowType(QtCore.Qt.UpArrow)
        self.upSuper.setObjectName("upSuper")
        self.downSuper = QtWidgets.QToolButton(self.groupBoxSuper)
        self.downSuper.setGeometry(QtCore.QRect(100, 100, 21, 21))
        self.downSuper.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.downSuper.setArrowType(QtCore.Qt.DownArrow)
        self.downSuper.setObjectName("downSuper")
        self.rightSuper = QtWidgets.QToolButton(self.groupBoxSuper)
        self.rightSuper.setGeometry(QtCore.QRect(120, 80, 21, 21))
        self.rightSuper.setArrowType(QtCore.Qt.RightArrow)
        self.rightSuper.setObjectName("rightSuper")
        self.label_9 = QtWidgets.QLabel(optionWindow)
        self.label_9.setGeometry(QtCore.QRect(170, 260, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.retranslateUi(optionWindow)
        QtCore.QMetaObject.connectSlotsByName(optionWindow)

    def retranslateUi(self, optionWindow):
        _translate = QtCore.QCoreApplication.translate
        optionWindow.setWindowTitle(_translate("optionWindow", "Menu des options"))
        self.label_5.setText(_translate("optionWindow", "Image Gauche"))
        self.label_6.setText(_translate("optionWindow", "Image Droite"))
        self.importToolRed.setText(_translate("optionWindow", "..."))
        self.boxOrientationRouge.setItemText(0, _translate("optionWindow", "Paysage"))
        self.boxOrientationRouge.setItemText(1, _translate("optionWindow", "Portrait"))
        self.boxOrientationRouge.setItemText(2, _translate("optionWindow", "Paysage renversé"))
        self.boxOrientationRouge.setItemText(3, _translate("optionWindow", "Portrait renversé"))
        self.label.setText(_translate("optionWindow", "Orientation"))
        self.label_2.setText(_translate("optionWindow", "Effet miroir"))
        self.boxMiroirRouge.setItemText(0, _translate("optionWindow", "Aucun"))
        self.boxMiroirRouge.setItemText(1, _translate("optionWindow", "Horizontal"))
        self.boxMiroirRouge.setItemText(2, _translate("optionWindow", "Vertical"))
        self.origineRed.setText(_translate("optionWindow", "Origine"))
        self.importToolCyan.setText(_translate("optionWindow", "..."))
        self.label_4.setText(_translate("optionWindow", "Effet miroir"))
        self.label_3.setText(_translate("optionWindow", "Orientation"))
        self.boxMiroirCyan.setItemText(0, _translate("optionWindow", "Aucun"))
        self.boxMiroirCyan.setItemText(1, _translate("optionWindow", "Horizontal"))
        self.boxMiroirCyan.setItemText(2, _translate("optionWindow", "Vertical"))
        self.boxOrientationCyan.setItemText(0, _translate("optionWindow", "Paysage"))
        self.boxOrientationCyan.setItemText(1, _translate("optionWindow", "Portrait"))
        self.boxOrientationCyan.setItemText(2, _translate("optionWindow", "Paysage renversé"))
        self.boxOrientationCyan.setItemText(3, _translate("optionWindow", "Portrait renversé"))
        self.origineCyan.setText(_translate("optionWindow", "Origine"))
        self.boxSuper.setText(_translate("optionWindow", "Activé"))
        self.radioCouleur.setText(_translate("optionWindow", "Couleur"))
        self.radioNoirBlanc.setText(_translate("optionWindow", "Noir et blanc"))
        self.saveSuper.setText(_translate("optionWindow", "Enregister"))
        self.origineSuper.setText(_translate("optionWindow", "Origine"))
        self.label_9.setText(_translate("optionWindow", "Superposition"))

class dropedit(QtWidgets.QGroupBox):   

    def __init__(self, parent=None):
        super(dropedit, self).__init__(parent)
        self.setAcceptDrops(True)

    def dragEnterEvent(self, event):
        event.accept()
        
    def dropEvent(self, event):
        fileURL = event.mimeData().urls()[0].toString()
        try :
            fileName = fileURL.split('file:///')[1]
        except :
            fileName = fileURL.split('file:')[1]
        for child in self.children(): 
            if child.metaObject().className() == "QLineEdit":
                child.setText(fileName)



class optionWindow(QtWidgets.QMainWindow): 
    closeWindow = pyqtSignal()
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.ui = Ui_optionWindow()
        self.ui.setupUi(self)
        self.ui.importToolCyan.clicked.connect(self.showImportCyan)
        self.ui.importToolRed.clicked.connect(self.showImportRed)

    def showImportCyan(self) :
        fname = QtWidgets.QFileDialog.getOpenFileName(self, 'Import picture', os.path.dirname(os.path.abspath(__file__)),"Image (*.png, *.jpg)")[0]
        if fname:
            self.ui.importLineCyan.setText(fname)

    def showImportRed(self) :
        fname = QtWidgets.QFileDialog.getOpenFileName(self, 'Import picture', os.path.dirname(os.path.abspath(__file__)), "Image (*.png, *.jpg)")[0]
        if fname:
            self.ui.importLineRed.setText(fname)

    def closeEvent(self,event):
        self.closeWindow.emit()




