name: Question générale
description: Créez un billet pour toutes questions liées au développement et aux mises à jour
labels: 
  - 'question'

body:
  - type: textarea
    id: zone-suggestion
    attributes:
      label: Expliquez comment nous pouvons répondre à votre question. N'oubliez pas d'inclure le plus d'informations possibles pour que votre question soit claire et complète. Ajoutez des captures d'écrans si nécessaire.
    validations:
      required: true
