# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\ui-optionWindow_VersionDock.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets
from qgis.PyQt.QtCore import pyqtSignal
import os
from qgis.utils import iface
from qgis.core import QgsMapLayerType, QgsWkbTypes
from . import resources
from .ui_getVectorLayer import getVectorLayer

class Ui_StereoDockWidget(object):
    def setupUi(self, StereoDockWidget):
        StereoDockWidget.setObjectName("StereoDockWidget")
        StereoDockWidget.resize(440, 420)
        StereoDockWidget.setMinimumSize(QtCore.QSize(165, 390))
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.groupBoxMainPath = dropedit(self.dockWidgetContents)
        self.groupBoxMainPath.setGeometry(QtCore.QRect(20, 10, 401, 45))
        self.groupBoxMainPath.setObjectName("groupBoxMainPath")
        self.importLineProject = QtWidgets.QLineEdit(self.groupBoxMainPath)
        self.importLineProject.setGeometry(QtCore.QRect(40, 20, 311, 20))
        self.importLineProject.setText("")
        self.importLineProject.setReadOnly(True)
        self.importLineProject.setObjectName("importLineProject")
        self.importToolProject = QtWidgets.QToolButton(self.groupBoxMainPath)
        self.importToolProject.setGeometry(QtCore.QRect(350, 20, 25, 19))
        self.importToolProject.setObjectName("importToolProject")
        self.groupBoxLeft = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBoxLeft.setGeometry(QtCore.QRect(20, 70, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxLeft.setFont(font)
        self.groupBoxLeft.setObjectName("groupBoxLeft")
        self.label_8 = QtWidgets.QLabel(self.groupBoxLeft)
        self.label_8.setGeometry(QtCore.QRect(20, 45, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.spinBoxLeftScreen = QtWidgets.QSpinBox(self.groupBoxLeft)
        self.spinBoxLeftScreen.setGeometry(QtCore.QRect(131, 45, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxLeftScreen.setFont(font)
        self.spinBoxLeftScreen.setMaximum(0)
        self.spinBoxLeftScreen.setObjectName("spinBoxLeftScreen")
        self.labelLeftName = QtWidgets.QLabel(self.groupBoxLeft)
        self.labelLeftName.setGeometry(QtCore.QRect(20, 20, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelLeftName.setFont(font)
        self.labelLeftName.setText("")
        self.labelLeftName.setObjectName("labelLeftName")
        self.groupBoxRight = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBoxRight.setGeometry(QtCore.QRect(20, 150, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxRight.setFont(font)
        self.groupBoxRight.setObjectName("groupBoxRight")
        self.label_9 = QtWidgets.QLabel(self.groupBoxRight)
        self.label_9.setGeometry(QtCore.QRect(20, 45, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.spinBoxRightScreen = QtWidgets.QSpinBox(self.groupBoxRight)
        self.spinBoxRightScreen.setGeometry(QtCore.QRect(131, 45, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxRightScreen.setFont(font)
        self.spinBoxRightScreen.setMaximum(0)
        self.spinBoxRightScreen.setObjectName("spinBoxRightScreen")
        self.labelRightName = QtWidgets.QLabel(self.groupBoxRight)
        self.labelRightName.setGeometry(QtCore.QRect(20, 20, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelRightName.setFont(font)
        self.labelRightName.setText("")
        self.labelRightName.setObjectName("labelRightName")
        self.toolButtonEst = QtWidgets.QToolButton(self.dockWidgetContents)
        self.toolButtonEst.setEnabled(False)
        self.toolButtonEst.setGeometry(QtCore.QRect(330, 90, 66, 23))
        self.toolButtonEst.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonEst.setAutoRaise(False)
        self.toolButtonEst.setArrowType(QtCore.Qt.RightArrow)
        self.toolButtonEst.setObjectName("toolButtonEst")
        self.toolButtonOuest = QtWidgets.QToolButton(self.dockWidgetContents)
        self.toolButtonOuest.setEnabled(False)
        self.toolButtonOuest.setGeometry(QtCore.QRect(230, 90, 81, 23))
        self.toolButtonOuest.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonOuest.setAutoRaise(False)
        self.toolButtonOuest.setArrowType(QtCore.Qt.LeftArrow)
        self.toolButtonOuest.setObjectName("toolButtonOuest")
        self.toolButtonSud = QtWidgets.QToolButton(self.dockWidgetContents)
        self.toolButtonSud.setEnabled(False)
        self.toolButtonSud.setGeometry(QtCore.QRect(290, 120, 71, 23))
        self.toolButtonSud.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonSud.setAutoRaise(False)
        self.toolButtonSud.setArrowType(QtCore.Qt.DownArrow)
        self.toolButtonSud.setObjectName("toolButtonSud")
        self.toolButtonNord = QtWidgets.QToolButton(self.dockWidgetContents)
        self.toolButtonNord.setEnabled(False)
        self.toolButtonNord.setGeometry(QtCore.QRect(280, 60, 81, 23))
        self.toolButtonNord.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonNord.setAutoRaise(False)
        self.toolButtonNord.setArrowType(QtCore.Qt.UpArrow)
        self.toolButtonNord.setObjectName("toolButtonNord")
        self.label_10 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(10, 260, 111, 16))
        self.label_10.setObjectName("label_10")
        self.pushButtonShowIDList = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonShowIDList.setEnabled(False)
        self.pushButtonShowIDList.setGeometry(QtCore.QRect(270, 150, 101, 23))
        self.pushButtonShowIDList.setObjectName("pushButtonShowIDList")
        self.enhanceButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.enhanceButton.setEnabled(False)
        self.enhanceButton.setGeometry(QtCore.QRect(110, 330, 71, 23))
        self.enhanceButton.setCheckable(False)
        self.enhanceButton.setObjectName("enhanceButton")
        self.pushButtonShowPicture = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonShowPicture.setEnabled(False)
        self.pushButtonShowPicture.setGeometry(QtCore.QRect(50, 370, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonShowPicture.setFont(font)
        self.pushButtonShowPicture.setObjectName("pushButtonShowPicture")
        self.spinBoxRecouvrementH = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBoxRecouvrementH.setGeometry(QtCore.QRect(130, 260, 51, 22))
        self.spinBoxRecouvrementH.setMaximum(100)
        self.spinBoxRecouvrementH.setProperty("value", 40)
        self.spinBoxRecouvrementH.setObjectName("spinBoxRecouvrementH")
        self.importLineVectorLayer = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.importLineVectorLayer.setEnabled(True)
        self.importLineVectorLayer.setGeometry(QtCore.QRect(60, 230, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.importLineVectorLayer.setFont(font)
        self.importLineVectorLayer.setText("")
        self.importLineVectorLayer.setReadOnly(True)
        self.importLineVectorLayer.setObjectName("importLineVectorLayer")
        self.importToolVectorLayer = QtWidgets.QToolButton(self.dockWidgetContents)
        self.importToolVectorLayer.setGeometry(QtCore.QRect(200, 230, 25, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.importToolVectorLayer.setFont(font)
        self.importToolVectorLayer.setObjectName("importToolVectorLayer")
        self.pushButtonRemoveShape = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonRemoveShape.setEnabled(False)
        self.pushButtonRemoveShape.setGeometry(QtCore.QRect(10, 330, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonRemoveShape.setFont(font)
        self.pushButtonRemoveShape.setObjectName("pushButtonRemoveShape")
        self.label_11 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(10, 230, 71, 16))
        self.label_11.setObjectName("label_11")
        self.groupBoxMoveLine = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBoxMoveLine.setGeometry(QtCore.QRect(250, 180, 141, 121))
        self.groupBoxMoveLine.setObjectName("groupBoxMoveLine")
        self.spinBoxMoveInY = QtWidgets.QSpinBox(self.groupBoxMoveLine)
        self.spinBoxMoveInY.setGeometry(QtCore.QRect(75, 90, 51, 22))
        self.spinBoxMoveInY.setObjectName("spinBoxMoveInY")
        self.spinBoxMoveInX = QtWidgets.QSpinBox(self.groupBoxMoveLine)
        self.spinBoxMoveInX.setGeometry(QtCore.QRect(75, 60, 51, 22))
        self.spinBoxMoveInX.setProperty("value", 5)
        self.spinBoxMoveInX.setObjectName("spinBoxMoveInX")
        self.checkBoxMoveLeft = QtWidgets.QCheckBox(self.groupBoxMoveLine)
        self.checkBoxMoveLeft.setGeometry(QtCore.QRect(10, 30, 61, 18))
        self.checkBoxMoveLeft.setChecked(True)
        self.checkBoxMoveLeft.setObjectName("checkBoxMoveLeft")
        self.checkBoxMoveRight = QtWidgets.QCheckBox(self.groupBoxMoveLine)
        self.checkBoxMoveRight.setGeometry(QtCore.QRect(70, 30, 51, 18))
        self.checkBoxMoveRight.setChecked(True)
        self.checkBoxMoveRight.setObjectName("checkBoxMoveRight")
        self.label_16 = QtWidgets.QLabel(self.groupBoxMoveLine)
        self.label_16.setGeometry(QtCore.QRect(5, 60, 71, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBoxMoveLine)
        self.label_17.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_17.setObjectName("label_17")
        self.label_14 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_14.setGeometry(QtCore.QRect(190, 330, 191, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_15.setGeometry(QtCore.QRect(190, 350, 211, 21))
        self.label_15.setObjectName("label_15")
        self.label_18 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_18.setGeometry(QtCore.QRect(190, 370, 211, 21))
        self.label_18.setObjectName("label_18")
        self.importToolMNT = QtWidgets.QToolButton(self.dockWidgetContents)
        self.importToolMNT.setGeometry(QtCore.QRect(200, 290, 25, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.importToolMNT.setFont(font)
        self.importToolMNT.setObjectName("importToolMNT")
        self.importLineMNT = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.importLineMNT.setEnabled(True)
        self.importLineMNT.setGeometry(QtCore.QRect(60, 290, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.importLineMNT.setFont(font)
        self.importLineMNT.setText("")
        self.importLineMNT.setReadOnly(True)
        self.importLineMNT.setObjectName("importLineMNT")
        self.label_12 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(10, 290, 71, 16))
        self.label_12.setObjectName("label_12")
        StereoDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(StereoDockWidget)
        QtCore.QMetaObject.connectSlotsByName(StereoDockWidget)

    def retranslateUi(self, StereoDockWidget):
        _translate = QtCore.QCoreApplication.translate
        StereoDockWidget.setWindowTitle(_translate("StereoDockWidget", "StereoPhoto"))
        self.groupBoxMainPath.setTitle(_translate("StereoDockWidget", "Chemin vers les photos"))
        self.importToolProject.setText(_translate("StereoDockWidget", "..."))
        self.groupBoxLeft.setTitle(_translate("StereoDockWidget", "Image Gauche"))
        self.label_8.setText(_translate("StereoDockWidget", "Numéro de l\'écran :"))
        self.groupBoxRight.setTitle(_translate("StereoDockWidget", "Image Droite"))
        self.label_9.setText(_translate("StereoDockWidget", "Numéro de l\'écran :"))
        self.toolButtonEst.setText(_translate("StereoDockWidget", "Est (D)"))
        self.toolButtonOuest.setText(_translate("StereoDockWidget", "Ouest (A)"))
        self.toolButtonSud.setText(_translate("StereoDockWidget", "Sud (S)"))
        self.toolButtonNord.setText(_translate("StereoDockWidget", "Nord (W)"))
        self.label_10.setText(_translate("StereoDockWidget", "Pourcentage à retirer : "))
        self.pushButtonShowIDList.setText(_translate("StereoDockWidget", "Parcourir la liste"))
        self.enhanceButton.setText(_translate("StereoDockWidget", "Rehausser"))
        self.pushButtonShowPicture.setText(_translate("StereoDockWidget", "Naviguer"))
        self.importToolVectorLayer.setText(_translate("StereoDockWidget", "..."))
        self.pushButtonRemoveShape.setText(_translate("StereoDockWidget", "Retirer la couche"))
        self.label_11.setText(_translate("StereoDockWidget", "Polygones"))
        self.groupBoxMoveLine.setTitle(_translate("StereoDockWidget", "Options de déplacement"))
        self.checkBoxMoveLeft.setText(_translate("StereoDockWidget", "Gauche"))
        self.checkBoxMoveRight.setText(_translate("StereoDockWidget", "Droite"))
        self.label_16.setText(_translate("StereoDockWidget", "Horizontal (X)"))
        self.label_17.setText(_translate("StereoDockWidget", "Vertical (Y)"))
        self.label_14.setText(_translate("StereoDockWidget", "Roulette + CTRL : Zoom avant/arrière"))
        self.label_15.setText(_translate("StereoDockWidget", "Roulette + SHIFT : Déplacement verticale"))
        self.label_18.setText(_translate("StereoDockWidget", "Roulette + Z : Déplacement des polygones"))
        self.importToolMNT.setText(_translate("StereoDockWidget", "..."))
        self.label_12.setText(_translate("StereoDockWidget", "MNT"))


class dropedit(QtWidgets.QGroupBox):   

    def __init__(self, parent=None):
        super(dropedit, self).__init__(parent)
        self.setAcceptDrops(True)

    def dragEnterEvent(self, event):
        event.accept()
        
    def dropEvent(self, event):
        fileURL = event.mimeData().urls()[0].toString()
        try :
            fileName = fileURL.split('file:///')[1]
        except :
            fileName = fileURL.split('file:')[1]
        if os.path.isdir(fileName):
            for child in self.children(): 
                if child.metaObject().className() == "QLineEdit":
                    child.setText(fileName)

class optionWindow(QtWidgets.QDockWidget): 
    closeWindow = pyqtSignal()
    keyDrawEvent = pyqtSignal(str)
    def __init__(self, iface):
        QtWidgets.QMainWindow.__init__(self, iface.mainWindow())
        self.ui = Ui_StereoDockWidget()
        self.ui.setupUi(self)
        self.ui.importToolProject.clicked.connect(self.showImportDirectory)
        self.ui.importToolVectorLayer.clicked.connect(self.showImportVector)
        self.ui.importToolMNT.clicked.connect(self.showImportMNT)
        self.ctrlClick = False
        self.shiftClick = False
        self.altClick = False
        self.vLayer = None
        self.currentMNTPath = ''

    #
    def showImportDirectory(self) :
        fname = QtWidgets.QFileDialog.getExistingDirectory(self, 'Importer un dossier de photos aériennes', os.path.dirname(os.path.abspath(__file__)))
        if fname:
            self.ui.importLineProject.setText(fname)

            
    #Ouvre une fenêtre de Qt pour choisir la couche de polygones
    def showImportVector(self):
        self.dictLayerName = {}
        for item in iface.mapCanvas().layers():
            if item.type() == QgsMapLayerType.VectorLayer and item.geometryType() == QgsWkbTypes.PolygonGeometry: 
                self.dictLayerName[item.name()] = item
        
        if self.dictLayerName : 
            self.vectorWindow = getVectorLayer(self.dictLayerName)
            self.vectorWindow.show()
            self.vectorWindow.ui.buttonBox.accepted.connect(self.importVectorAccept)
            self.vectorWindow.ui.buttonBox.rejected.connect(self.importVectorCancel)

        else :
            #No Current VectorLayer
            return

    #Création de l'objet qui réprésente la couche vectorielle
    def importVectorAccept(self):
        vLayerName = self.vectorWindow.ui.listWidget.selectedItems()[0].text()
        self.vLayer = self.dictLayerName[vLayerName]
        self.ui.importLineVectorLayer.setText(vLayerName)
        self.vectorWindow.close()

    def importVectorCancel(self):
        self.vectorWindow.close()

    def showImportMNT(self):
        fname = QtWidgets.QFileDialog.getOpenFileName(self, 'Importer un modèle numérique de terrain', os.path.dirname(os.path.abspath(__file__)), 'MNT (*tif)')[0]
        if fname:
            self.currentMNTPath = fname
            nameMNT = os.path.basename(fname)
            self.ui.importLineMNT.setText(nameMNT)
        else : 
            self.currentMNTPath = ''

        
    
    def closeEvent(self,event):
        self.closeWindow.emit()

    #Fonction appelé lorsqu'une touche du clavier est appuyée
    def keyPressEvent(self, event):
        if event.key() == QtCore.Qt.Key_Control:
            self.ctrlClick = True
        elif event.key() == QtCore.Qt.Key_Shift :
            self.shiftClick = True
        elif event.key() == QtCore.Qt.Key_Z:    
            self.altClick = True
        elif event.key() == QtCore.Qt.Key_W:
            self.keyDrawEvent.emit("N")
        elif event.key() == QtCore.Qt.Key_A :
            self.keyDrawEvent.emit("O") 
        elif event.key() == QtCore.Qt.Key_S :
            self.keyDrawEvent.emit("S") 
        elif event.key() == QtCore.Qt.Key_D :
            self.keyDrawEvent.emit("E") 
        elif event.key() == QtCore.Qt.Key_Escape:
            self.keyDrawEvent.emit("ESC")

    def keyReleaseEvent(self, event):
        self.ctrlClick = False
        self.shiftClick = False
        self.altClick = False

