# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\ui-optionWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from qgis.PyQt import QtCore, QtGui, QtWidgets
from qgis.PyQt.QtCore import pyqtSignal
import os
from qgis.utils import iface
from qgis.core import QgsMapLayerType, QgsWkbTypes
from . import resources
from .ui_getVectorLayer import getVectorLayer

class Ui_StereoDockWidget(object):
    def setupUi(self, StereoDockWidget):
        StereoDockWidget.setObjectName("StereoDockWidget")
        StereoDockWidget.resize(434, 342)
        StereoDockWidget.setMinimumSize(QtCore.QSize(165, 200))
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.groupBoxMainPath = dropedit(self.dockWidgetContents)
        self.groupBoxMainPath.setGeometry(QtCore.QRect(20, 10, 401, 45))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxMainPath.setFont(font)
        self.groupBoxMainPath.setObjectName("groupBoxMainPath")
        self.importLineProject = QtWidgets.QLineEdit(self.groupBoxMainPath)
        self.importLineProject.setGeometry(QtCore.QRect(40, 20, 311, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.importLineProject.setFont(font)
        self.importLineProject.setText("")
        self.importLineProject.setReadOnly(True)
        self.importLineProject.setObjectName("importLineProject")
        self.importToolProject = QtWidgets.QToolButton(self.groupBoxMainPath)
        self.importToolProject.setGeometry(QtCore.QRect(350, 20, 25, 19))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.importToolProject.setFont(font)
        self.importToolProject.setObjectName("importToolProject")
        self.toolButtonEst = QtWidgets.QToolButton(self.dockWidgetContents)
        self.toolButtonEst.setEnabled(False)
        self.toolButtonEst.setGeometry(QtCore.QRect(350, 90, 66, 23))
        self.toolButtonEst.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonEst.setAutoRaise(False)
        self.toolButtonEst.setArrowType(QtCore.Qt.RightArrow)
        self.toolButtonEst.setObjectName("toolButtonEst")
        self.toolButtonOuest = QtWidgets.QToolButton(self.dockWidgetContents)
        self.toolButtonOuest.setEnabled(False)
        self.toolButtonOuest.setGeometry(QtCore.QRect(260, 90, 81, 23))
        self.toolButtonOuest.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonOuest.setAutoRaise(False)
        self.toolButtonOuest.setArrowType(QtCore.Qt.LeftArrow)
        self.toolButtonOuest.setObjectName("toolButtonOuest")
        self.toolButtonSud = QtWidgets.QToolButton(self.dockWidgetContents)
        self.toolButtonSud.setEnabled(False)
        self.toolButtonSud.setGeometry(QtCore.QRect(310, 120, 71, 23))
        self.toolButtonSud.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonSud.setAutoRaise(False)
        self.toolButtonSud.setArrowType(QtCore.Qt.DownArrow)
        self.toolButtonSud.setObjectName("toolButtonSud")
        self.toolButtonNord = QtWidgets.QToolButton(self.dockWidgetContents)
        self.toolButtonNord.setEnabled(False)
        self.toolButtonNord.setGeometry(QtCore.QRect(300, 60, 81, 23))
        self.toolButtonNord.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonNord.setAutoRaise(False)
        self.toolButtonNord.setArrowType(QtCore.Qt.UpArrow)
        self.toolButtonNord.setObjectName("toolButtonNord")
        self.label_10 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(10, 190, 111, 16))
        self.label_10.setObjectName("label_10")
        self.pushButtonShowIDList = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonShowIDList.setEnabled(False)
        self.pushButtonShowIDList.setGeometry(QtCore.QRect(290, 150, 101, 23))
        self.pushButtonShowIDList.setObjectName("pushButtonShowIDList")
        self.enhanceButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.enhanceButton.setEnabled(False)
        self.enhanceButton.setGeometry(QtCore.QRect(30, 230, 71, 23))
        self.enhanceButton.setCheckable(False)
        self.enhanceButton.setObjectName("enhanceButton")
        self.pushButtonShowPicture = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonShowPicture.setEnabled(False)
        self.pushButtonShowPicture.setGeometry(QtCore.QRect(60, 270, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonShowPicture.setFont(font)
        self.pushButtonShowPicture.setObjectName("pushButtonShowPicture")
        self.spinBoxRecouvrementH = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBoxRecouvrementH.setGeometry(QtCore.QRect(140, 190, 51, 22))
        self.spinBoxRecouvrementH.setMaximum(100)
        self.spinBoxRecouvrementH.setProperty("value", 40)
        self.spinBoxRecouvrementH.setObjectName("spinBoxRecouvrementH")
        self.importLineVectorLayer = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.importLineVectorLayer.setEnabled(True)
        self.importLineVectorLayer.setGeometry(QtCore.QRect(70, 130, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.importLineVectorLayer.setFont(font)
        self.importLineVectorLayer.setText("")
        self.importLineVectorLayer.setReadOnly(True)
        self.importLineVectorLayer.setObjectName("importLineVectorLayer")
        self.importToolVectorLayer = QtWidgets.QToolButton(self.dockWidgetContents)
        self.importToolVectorLayer.setGeometry(QtCore.QRect(210, 130, 25, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.importToolVectorLayer.setFont(font)
        self.importToolVectorLayer.setObjectName("importToolVectorLayer")
        self.pushButtonRemoveShape = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonRemoveShape.setEnabled(False)
        self.pushButtonRemoveShape.setGeometry(QtCore.QRect(10, 160, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonRemoveShape.setFont(font)
        self.pushButtonRemoveShape.setObjectName("pushButtonRemoveShape")
        self.label_11 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(10, 130, 71, 16))
        self.label_11.setObjectName("label_11")
        self.groupBoxMNT = dropEventMNT(self.dockWidgetContents)
        self.groupBoxMNT.setGeometry(QtCore.QRect(210, 190, 201, 91))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxMNT.setFont(font)
        self.groupBoxMNT.setObjectName("groupBox")
        self.radioButtonDraw = QtWidgets.QRadioButton(self.groupBoxMNT)
        self.radioButtonDraw.setEnabled(False)
        self.radioButtonDraw.setGeometry(QtCore.QRect(20, 60, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioButtonDraw.setFont(font)
        self.radioButtonDraw.setChecked(True)
        self.radioButtonDraw.setEnabled(False)
        self.radioButtonDraw.setObjectName("radioButtonDraw")
        self.radioButtonCut = QtWidgets.QRadioButton(self.groupBoxMNT)
        self.radioButtonCut.setGeometry(QtCore.QRect(90, 60, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioButtonCut.setFont(font)
        self.radioButtonCut.setEnabled(False)
        self.radioButtonCut.setObjectName("radioButtonCut")
        self.importToolMNT = QtWidgets.QToolButton(self.groupBoxMNT)
        self.importToolMNT.setGeometry(QtCore.QRect(170, 20, 25, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.importToolMNT.setFont(font)
        self.importToolMNT.setObjectName("importToolMNT")
        self.importLineMNT = QtWidgets.QLineEdit(self.groupBoxMNT)
        self.importLineMNT.setGeometry(QtCore.QRect(10, 20, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.importLineMNT.setFont(font)
        self.importLineMNT.setText("")
        self.importLineMNT.setReadOnly(True)
        self.importLineMNT.setObjectName("importLineMNT")
        self.pushButtonOpenParam = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonOpenParam.setGeometry(QtCore.QRect(110, 230, 75, 23))
        self.pushButtonOpenParam.setObjectName("pushButtonOpenParam")
        self.labelRightName = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelRightName.setGeometry(QtCore.QRect(110, 100, 141, 16))
        self.labelRightName.setText("")
        self.labelRightName.setObjectName("labelRightName")
        self.labelLeftName = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelLeftName.setGeometry(QtCore.QRect(110, 70, 141, 20))
        self.labelLeftName.setText("")
        self.labelLeftName.setObjectName("labelLeftName")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(10, 70, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        StereoDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(StereoDockWidget)
        QtCore.QMetaObject.connectSlotsByName(StereoDockWidget)

    def retranslateUi(self, StereoDockWidget):
        _translate = QtCore.QCoreApplication.translate
        StereoDockWidget.setWindowTitle(_translate("StereoDockWidget", "StereoPhoto"))
        self.groupBoxMainPath.setTitle(_translate("StereoDockWidget", "Chemin vers les photos"))
        self.importToolProject.setText(_translate("StereoDockWidget", "..."))
        self.toolButtonEst.setText(_translate("StereoDockWidget", "Est (D)"))
        self.toolButtonOuest.setText(_translate("StereoDockWidget", "Ouest (A)"))
        self.toolButtonSud.setText(_translate("StereoDockWidget", "Sud (S)"))
        self.toolButtonNord.setText(_translate("StereoDockWidget", "Nord (W)"))
        self.label_10.setText(_translate("StereoDockWidget", "Pourcentage à retirer : "))
        self.pushButtonShowIDList.setText(_translate("StereoDockWidget", "Parcourir la liste"))
        self.enhanceButton.setText(_translate("StereoDockWidget", "Rehausser"))
        self.pushButtonShowPicture.setText(_translate("StereoDockWidget", "Naviguer"))
        self.importToolVectorLayer.setText(_translate("StereoDockWidget", "..."))
        self.pushButtonRemoveShape.setText(_translate("StereoDockWidget", "Retirer la couche"))
        self.label_11.setText(_translate("StereoDockWidget", "Polygones"))
        self.groupBoxMNT.setTitle(_translate("StereoDockWidget", "Modèle numérique de terrrain"))
        self.radioButtonDraw.setText(_translate("StereoDockWidget", "Dessiner"))
        self.radioButtonCut.setText(_translate("StereoDockWidget", "Découper"))
        self.importToolMNT.setText(_translate("StereoDockWidget", "..."))
        self.pushButtonOpenParam.setText(_translate("StereoDockWidget", "Paramètres"))
        self.label.setText(_translate("StereoDockWidget", "Image Gauche :"))
        self.label_2.setText(_translate("StereoDockWidget", "Image Droite :"))

class dropEventMNT(QtWidgets.QGroupBox): 
    validMNT = pyqtSignal()
    def __init__(self, parent=None):
        QtWidgets.QGroupBox.__init__(self, parent)
        self.setAcceptDrops(True)

    def dragEnterEvent(self, event):
        event.accept()
        
    def dropEvent(self, event):
        fileURL = event.mimeData().urls()[0].toString()
        try :
            fileName = fileURL.split('file:///')[1]
        except :
            fileName = fileURL.split('file:')[1]
        
        
        if fileName.split('.')[-1] == 'tif':
            self.MNTPath = fileName
            self.MNTName = os.path.basename(fileName)
            self.validMNT.emit()
        else : 
            self.MNTPath = ''
            self.MNTName = ''

class dropedit(QtWidgets.QGroupBox):   

    def __init__(self, parent=None):
        super(dropedit, self).__init__(parent)
        self.setAcceptDrops(True)

    def dragEnterEvent(self, event):
        event.accept()
        
    def dropEvent(self, event):
        fileURL = event.mimeData().urls()[0].toString()
        try :
            fileName = fileURL.split('file:///')[1]
        except :
            fileName = fileURL.split('file:')[1]
        if os.path.isdir(fileName):
            for child in self.children(): 
                if child.metaObject().className() == "QLineEdit":
                    child.setText(fileName)

class optionWindow(QtWidgets.QDockWidget): 
    closeWindow = pyqtSignal()
    keyPressed = pyqtSignal(QtGui.QKeyEvent)
    def __init__(self, iface):
        QtWidgets.QMainWindow.__init__(self, iface.mainWindow())
        self.ui = Ui_StereoDockWidget()
        self.ui.setupUi(self)
        self.ui.importToolProject.clicked.connect(self.showImportDirectory)
        self.ui.importToolVectorLayer.clicked.connect(self.showImportVector)
        self.ui.importToolMNT.clicked.connect(self.showImportMNT)
        self.ui.groupBoxMNT.validMNT.connect(self.dropImportMNT)
        self.vLayer = None
        self.currentMNTPath = ''

    def showImportDirectory(self) :
        fname = QtWidgets.QFileDialog.getExistingDirectory(self, 'Importer un dossier de photos aériennes', os.path.dirname(os.path.abspath(__file__)))
        if fname:
            self.ui.importLineProject.setText(fname)

            
    #Ouvre une fenêtre de Qt pour choisir la couche de polygones
    def showImportVector(self):
        self.dictLayerName = {}
        for item in iface.mapCanvas().layers():
            if item.type() == QgsMapLayerType.VectorLayer and item.geometryType() == QgsWkbTypes.PolygonGeometry: 
                self.dictLayerName[item.name()] = item
        
        if self.dictLayerName : 
            self.vectorWindow = getVectorLayer(self.dictLayerName)
            self.vectorWindow.show()
            self.vectorWindow.ui.buttonBox.accepted.connect(self.importVectorAccept)
            self.vectorWindow.ui.buttonBox.rejected.connect(self.importVectorCancel)

        else :
            #No Current VectorLayer
            return

    #Création de l'objet qui réprésente la couche vectorielle
    def importVectorAccept(self):
        vLayerName = self.vectorWindow.ui.listWidget.selectedItems()[0].text()
        self.vLayer = self.dictLayerName[vLayerName]
        self.ui.importLineVectorLayer.setText(vLayerName)
        self.vectorWindow.close()

    def importVectorCancel(self):
        self.vectorWindow.close()

    def showImportMNT(self):
        fname = QtWidgets.QFileDialog.getOpenFileName(self, 'Importer un modèle numérique de terrain', os.path.dirname(os.path.abspath(__file__)), 'MNT (*tif)')[0]
        if fname:
            self.currentMNTPath = fname
            nameMNT = os.path.basename(fname)
            self.ui.importLineMNT.setText(nameMNT)
            self.ui.radioButtonCut.setEnabled(True)
            self.ui.radioButtonDraw.setEnabled(True)
        else : 
            self.currentMNTPath = ''
            self.ui.radioButtonCut.setEnabled(False)
            self.ui.radioButtonDraw.setEnabled(False)
    
    def dropImportMNT(self):
        self.currentMNTPath = self.ui.groupBoxMNT.MNTPath
        self.ui.importLineMNT.setText(self.ui.groupBoxMNT.MNTName)
        self.ui.radioButtonCut.setEnabled(True)
        self.ui.radioButtonDraw.setEnabled(True)

    def closeEvent(self,event):
        self.closeWindow.emit()

    #Fonction appelé lorsqu'une touche du clavier est appuyée
    def keyPressEvent(self, event):
        self.keyPressed.emit(event)

    def keyReleaseEvent(self, event):
        self.keyPressed.emit(event)
        