# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui-optionWindow_smallSize_Layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from qgis.PyQt import QtCore, QtGui, QtWidgets
from qgis.PyQt.QtCore import pyqtSignal
import os, json, math
from urllib.parse import urlparse
from osgeo import gdal
import numpy as np
from qgis.utils import iface
from qgis.core import QgsMapLayerType, QgsWkbTypes
from . import resources
from .ui_getVectorLayer import getVectorLayerCustomList
from .ui_graphicsWindow import Ui_graphicsWindow 


class Ui_StereoDockWidget(object):
    def setupUi(self, StereoDockWidget):
        StereoDockWidget.setObjectName("StereoDockWidget")
        StereoDockWidget.resize(280, 604)
        StereoDockWidget.setMinimumSize(QtCore.QSize(279, 604))
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setContentsMargins(-1, 11, -1, 11)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxMainPath = dropedit(self.dockWidgetContents)
        self.groupBoxMainPath.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxMainPath.setFont(font)
        self.groupBoxMainPath.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxMainPath.setObjectName("groupBoxMainPath")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxMainPath)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.importLineProject = QtWidgets.QLineEdit(self.groupBoxMainPath)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.importLineProject.setFont(font)
        self.importLineProject.setText("")
        self.importLineProject.setReadOnly(True)
        self.importLineProject.setObjectName("importLineProject")
        self.gridLayout_3.addWidget(self.importLineProject, 0, 0, 1, 1)
        self.importToolProject = QtWidgets.QToolButton(self.groupBoxMainPath)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.importToolProject.setFont(font)
        self.importToolProject.setObjectName("importToolProject")
        self.gridLayout_3.addWidget(self.importToolProject, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBoxMainPath)
        self.frame = QtWidgets.QFrame(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(5, 5, 5, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.labelRightName = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(75)
        self.labelRightName.setFont(font)
        self.labelRightName.setText("")
        self.labelRightName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRightName.setObjectName("labelRightName")
        self.gridLayout.addWidget(self.labelRightName, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.labelLeftName = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(75)
        self.labelLeftName.setFont(font)
        self.labelLeftName.setText("")
        self.labelLeftName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLeftName.setObjectName("labelLeftName")
        self.gridLayout.addWidget(self.labelLeftName, 1, 0, 1, 1)
        self.checkBoxFlip = QtWidgets.QCheckBox(self.frame)
        self.checkBoxFlip.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxFlip.setObjectName("checkBoxFlip")
        self.gridLayout.addWidget(self.checkBoxFlip, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButtonFindBestPair = QtWidgets.QPushButton(self.frame)
        self.pushButtonFindBestPair.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonFindBestPair.setFont(font)
        self.pushButtonFindBestPair.setObjectName("pushButtonFindBestPair")
        self.gridLayout.addWidget(self.pushButtonFindBestPair, 7, 0, 1, 1)
        self.pushButtonShowIDList = QtWidgets.QPushButton(self.frame)
        self.pushButtonShowIDList.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonShowIDList.setFont(font)
        self.pushButtonShowIDList.setObjectName("pushButtonShowIDList")
        self.gridLayout.addWidget(self.pushButtonShowIDList, 7, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.spinBoxDownScreen = QtWidgets.QSpinBox(self.frame)
        self.spinBoxDownScreen.setObjectName("spinBoxDownScreen")
        self.gridLayout.addWidget(self.spinBoxDownScreen, 1, 1, 1, 1)
        self.spinBoxUpScreen = QtWidgets.QSpinBox(self.frame)
        self.spinBoxUpScreen.setObjectName("spinBoxUpScreen")
        self.gridLayout.addWidget(self.spinBoxUpScreen, 3, 1, 1, 1)
        self.pushButtonShowScreenNumber = QtWidgets.QPushButton(self.frame)
        self.pushButtonShowScreenNumber.setObjectName("pushButtonShowScreenNumber")
        self.gridLayout.addWidget(self.pushButtonShowScreenNumber, 4, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 400)
        self.gridLayout.setColumnStretch(1, 50)
        self.verticalLayout_2.addWidget(self.frame)
        self.enhanceButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.enhanceButton.setEnabled(False)
        self.enhanceButton.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enhanceButton.setFont(font)
        self.enhanceButton.setStyleSheet("\n"
"color: rgb(220, 147, 0);")
        self.enhanceButton.setCheckable(False)
        self.enhanceButton.setObjectName("enhanceButton")
        self.verticalLayout_2.addWidget(self.enhanceButton)
        self.pushButtonShowPicture = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonShowPicture.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonShowPicture.setFont(font)
        self.pushButtonShowPicture.setStyleSheet("color: rgb(0, 208, 0);")
        self.pushButtonShowPicture.setObjectName("pushButtonShowPicture")
        self.verticalLayout_2.addWidget(self.pushButtonShowPicture)
        self.pushButtonCloseWindow = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonCloseWindow.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCloseWindow.setFont(font)
        self.pushButtonCloseWindow.setStyleSheet("color: rgb(229, 0, 0);")
        self.pushButtonCloseWindow.setObjectName("pushButtonCloseWindow")
        self.verticalLayout_2.addWidget(self.pushButtonCloseWindow)
        self.pushButtonAffVecteur = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonAffVecteur.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButtonAffVecteur.setFont(font)
        self.pushButtonAffVecteur.setObjectName("pushButtonAffVecteur")
        self.verticalLayout_2.addWidget(self.pushButtonAffVecteur)
        self.label_11 = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.importLineVectorLayer = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.importLineVectorLayer.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.importLineVectorLayer.setFont(font)
        self.importLineVectorLayer.setText("")
        self.importLineVectorLayer.setReadOnly(True)
        self.importLineVectorLayer.setObjectName("importLineVectorLayer")
        self.verticalLayout_2.addWidget(self.importLineVectorLayer)
        self.groupBoxMNT = dropEventMNT(self.dockWidgetContents)
        self.groupBoxMNT.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxMNT.setFont(font)
        self.groupBoxMNT.setObjectName("groupBoxMNT")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxMNT)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.importLineMNT = QtWidgets.QLineEdit(self.groupBoxMNT)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.importLineMNT.setFont(font)
        self.importLineMNT.setText("")
        self.importLineMNT.setReadOnly(True)
        self.importLineMNT.setObjectName("importLineMNT")
        self.gridLayout_2.addWidget(self.importLineMNT, 0, 0, 1, 2)
        self.importToolMNT = QtWidgets.QToolButton(self.groupBoxMNT)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.importToolMNT.setFont(font)
        self.importToolMNT.setObjectName("importToolMNT")
        self.gridLayout_2.addWidget(self.importToolMNT, 0, 2, 1, 1)
        self.radioButtonDraw = QtWidgets.QRadioButton(self.groupBoxMNT)
        self.radioButtonDraw.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioButtonDraw.setFont(font)
        self.radioButtonDraw.setChecked(True)
        self.radioButtonDraw.setObjectName("radioButtonDraw")
        self.gridLayout_2.addWidget(self.radioButtonDraw, 1, 0, 1, 1)
        self.pushButtonRemoveMNT = QtWidgets.QPushButton(self.groupBoxMNT)
        self.pushButtonRemoveMNT.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonRemoveMNT.setFont(font)
        self.pushButtonRemoveMNT.setObjectName("pushButtonRemoveMNT")
        self.gridLayout_2.addWidget(self.pushButtonRemoveMNT, 1, 1, 2, 2)
        self.radioButtonCut = QtWidgets.QRadioButton(self.groupBoxMNT)
        self.radioButtonCut.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioButtonCut.setFont(font)
        self.radioButtonCut.setObjectName("radioButtonCut")
        self.gridLayout_2.addWidget(self.radioButtonCut, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBoxMNT)
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.labelAltitude = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAltitude.setFont(font)
        self.labelAltitude.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAltitude.setObjectName("labelAltitude")
        self.verticalLayout_2.addWidget(self.labelAltitude)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        StereoDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(StereoDockWidget)
        QtCore.QMetaObject.connectSlotsByName(StereoDockWidget)

    def retranslateUi(self, StereoDockWidget):
        _translate = QtCore.QCoreApplication.translate
        StereoDockWidget.setWindowTitle(_translate("StereoDockWidget", "StereoPhoto"))
        self.groupBoxMainPath.setTitle(_translate("StereoDockWidget", "Chemin vers les photos"))
        self.importToolProject.setText(_translate("StereoDockWidget", "..."))
        self.label_2.setText(_translate("StereoDockWidget", "Image du haut"))
        self.label.setText(_translate("StereoDockWidget", "Image du bas"))
        self.checkBoxFlip.setText(_translate("StereoDockWidget", "Retirer l\'effet miroir"))
        self.pushButtonFindBestPair.setText(_translate("StereoDockWidget", "Trouver la paire avec QGIS"))
        self.pushButtonShowIDList.setText(_translate("StereoDockWidget", "Liste Photo"))
        self.label_3.setText(_translate("StereoDockWidget", "Écran du haut"))
        self.label_4.setText(_translate("StereoDockWidget", "Écran du bas"))
        self.pushButtonShowScreenNumber.setText(_translate("StereoDockWidget", "Voir Numéro"))
        self.enhanceButton.setText(_translate("StereoDockWidget", "Rehausser"))
        self.pushButtonShowPicture.setText(_translate("StereoDockWidget", "Naviguer"))
        self.pushButtonCloseWindow.setText(_translate("StereoDockWidget", "Fermer"))
        self.pushButtonAffVecteur.setText(_translate("StereoDockWidget", "Gestion des couches vectorielles"))
        self.label_11.setText(_translate("StereoDockWidget", "Couche en édition"))
        self.groupBoxMNT.setTitle(_translate("StereoDockWidget", "Modèle numérique de terrrain"))
        self.importToolMNT.setText(_translate("StereoDockWidget", "..."))
        self.radioButtonDraw.setText(_translate("StereoDockWidget", "Dessiner"))
        self.pushButtonRemoveMNT.setText(_translate("StereoDockWidget", "Retirer le modèle"))
        self.radioButtonCut.setText(_translate("StereoDockWidget", "Découper"))
        self.label_5.setText(_translate("StereoDockWidget", "Altitude du curseur"))
        self.labelAltitude.setText(_translate("StereoDockWidget", "100.000000000"))



class dropEventMNT(QtWidgets.QGroupBox): 
    validMNT = pyqtSignal()
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setAcceptDrops(True)
        self.MNTPath = ""
        self.MNTName = ""
        self.fileExtensions = ['tif','vrt']

    def dragEnterEvent(self, event):
        if event.mimeData().hasUrls():
            event.acceptProposedAction()
        else:
            event.ignore()

    def dropEvent(self, event):
        urls = event.mimeData().urls()
        if not urls:
            event.ignore()
            return

        url = urls[0] 
        local = url.toLocalFile()
        if local:
            return local
        
        parsed = urlparse(url.toString())
        if parsed.scheme == "file" and parsed.path:
            if os.name == "nt" : 
                file_path = parsed.path.lstrip("/")  
            
            else : file_path = parsed.path
        
        else : 
            event.ignore()
            return

        ext = os.path.splitext(file_path)[1].lstrip(".").lower()
        if ext in self.fileExtensions:
            self.MNTPath = file_path
            self.MNTName = os.path.basename(file_path)
            self.validMNT.emit()
            event.acceptProposedAction()
        else:
            self.MNTPath = ""
            self.MNTName = ""
            event.ignore()

        

class dropedit(QtWidgets.QGroupBox):   

    def __init__(self, parent=None):
        super(dropedit, self).__init__(parent)
        self.setAcceptDrops(True)

    def dragEnterEvent(self, event):
        event.accept()
        
    def dropEvent(self, event):
        fileURL = event.mimeData().urls()[0].toString()
        try :
            fileName = fileURL.split('file:///')[1]
        except :
            fileName = fileURL.split('file:')[1]
        if os.path.isdir(fileName):
            for child in self.children(): 
                if child.metaObject().className() == "QLineEdit":
                    child.setText(fileName)

class optionWindow(QtWidgets.QDockWidget): 
    closeWindow = pyqtSignal()
    def __init__(self, iface):
        QtWidgets.QMainWindow.__init__(self, iface.mainWindow())
        self.ui = Ui_StereoDockWidget()
        self.ui.setupUi(self)
        self.ui.importToolProject.clicked.connect(self.showImportDirectory)
        self.ui.pushButtonAffVecteur.clicked.connect(self.showImportVector)
        self.ui.importToolMNT.clicked.connect(self.showImportMNT)
        self.ui.groupBoxMNT.validMNT.connect(self.dropImportMNT)
        self.ui.pushButtonRemoveMNT.clicked.connect(self.removeImportMNT)
        self.ui.pushButtonShowScreenNumber.clicked.connect(self.actionShowScreenNumber)
        self.vLayer = None
        self.vectorWindow = getVectorLayerCustomList()
        self.projectPath = os.path.expanduser("~")
        self.mntLocation = os.path.expanduser("~")

        self.JSONPath = os.path.join(os.path.dirname(os.path.realpath(__file__)),'paramStoring.json')

        self.listGraphWinObj = []
        self.screenNumberTimer = QtCore.QTimer(self)
        self.screenNumberTimer.setSingleShot(True)
        self.screenNumberTimer.timeout.connect(self.closeScreenWindow)

        
        #self.currentMNTPath = ''

    def showImportDirectory(self) :
        fname = QtWidgets.QFileDialog.getExistingDirectory(self, 'Importer un dossier de photos aériennes',self.projectPath)
        if fname: self.ui.importLineProject.setText(fname)

            
    #Ouvre une fenêtre de Qt pour choisir la couche de polygones
    def showImportVector(self):
        self.dictLayerName = {}
        for item in iface.mapCanvas().layers():
            if item.type() == QgsMapLayerType.VectorLayer and item.geometryType() in [QgsWkbTypes.PolygonGeometry, QgsWkbTypes.PointGeometry,QgsWkbTypes.LineGeometry]: 
                self.dictLayerName[item.name()] = item
        
        if self.dictLayerName : 
            self.vectorWindow.setItem(self.dictLayerName)
            self.vectorWindow.show()
            self.vectorWindow.raise_()
            self.vectorWindow.ui.buttonBox.accepted.connect(self.importVectorAccept)
            self.vectorWindow.ui.buttonBox.rejected.connect(self.importVectorCancel)

        else :
            #No Current VectorLayer
            return

    #Création de l'objet qui réprésente la couche vectorielle
    def importVectorAccept(self):
        self.vectorToShow = {}
        for i in range(self.vectorWindow.ui.tableWidget.rowCount()) : 
            afficher = self.vectorWindow.ui.tableWidget.cellWidget(i,0)
            nomCouche = self.vectorWindow.ui.tableWidget.item(i,1).text()
            couleur = self.vectorWindow.ui.tableWidget.cellWidget(i,2).property("color")
            utiliser3D = self.vectorWindow.ui.tableWidget.cellWidget(i,3).isChecked()
            if afficher.isChecked() : self.vectorToShow[nomCouche] = [couleur,utiliser3D]

        currentRow = self.vectorWindow.ui.tableWidget.currentRow()
        currentVectors = list(self.vectorToShow.keys())
        if len(currentVectors) > 0 : 
            if currentRow == -1  : editLayer = ''
            else : editLayer = self.vectorWindow.ui.tableWidget.item(currentRow,1).text()
            self.vLayerName = editLayer if editLayer in currentVectors else currentVectors[0]  
            #self.vLayerName = self.vectorWindow.ui.tableWidget.itemWidget(self.vectorWindow.ui.listWidget.selectedItems()[0]).label.text()
            self.vLayer = self.dictLayerName[self.vLayerName]
            self.ui.importLineVectorLayer.setText(self.vLayerName)
        self.vectorWindow.close()

    def importVectorCancel(self):
        self.vectorWindow.close()
    
    def showImportMNT(self):
        fname = QtWidgets.QFileDialog.getOpenFileName(self, 'Importer un modèle numérique de terrain', self.mntLocation, 'MNT (*.tif *.vrt)')[0]
        if fname:
            self.loadImportMNT(fname)
        else : 
            self.removeImportMNT()
    
    def dropImportMNT(self):
        self.loadImportMNT(self.ui.groupBoxMNT.MNTPath)
    
    def loadImportMNT(self, file):
        if not os.path.isfile(file):
            self.removeImportMNT()
            return
        
        self.currentMNTPath = file
        self.mntLocation = os.path.dirname(file)
        self.setStateMNT(True, os.path.basename(file))

    def getMNTWithCoord(self,rectCoord) :

        if self.currentMNTPath == "" : 
            self.mntArr = None
            return

        mntDS = gdal.Open(self.currentMNTPath,gdal.GA_ReadOnly)
        mntBand = mntDS.GetRasterBand(1)
        self.mntGeo = mntDS.GetGeoTransform()
        self.mntSize = (mntDS.RasterXSize, mntDS.RasterYSize)
        self.mntNodata = mntBand.GetNoDataValue()

        pxStart = math.floor((rectCoord.xMinimum() - self.mntGeo[0]) / self.mntGeo[1])
        pyStart = math.floor((rectCoord.yMaximum() - self.mntGeo[3]) / self.mntGeo[5])

        self.pxStart = pxStart
        self.pyStart = pyStart

        pxEnd = math.floor((rectCoord.xMaximum() - self.mntGeo[0]) / self.mntGeo[1])
        pyEnd = math.floor((rectCoord.yMinimum() - self.mntGeo[3]) / self.mntGeo[5])

        # Requested output size
        sizeX = pxEnd - pxStart
        sizeY = pyEnd - pyStart            
        mntArr = np.full((sizeY, sizeX), self.mntNodata, dtype=np.float32)

        if (pxStart >= self.mntSize[0] or pxStart + sizeX <= 0 or
            pyStart >= self.mntSize[1] or pyStart + sizeY <= 0):

            self.mntArr = mntArr


        else : 
            # Where the read starts *in the raster*
            read_xoff = max(0, pxStart)
            read_yoff = max(0, pyStart)

            # Where the read starts *inside the output array*
            arr_xoff = read_xoff-pxStart
            arr_yoff = read_yoff-pyStart

            # Compute read size inside raster bounds
            read_xsize = min(pxStart + sizeX, self.mntSize[0]) - read_xoff
            read_ysize = min(pyStart + sizeY, self.mntSize[1]) - read_yoff

            if read_xsize > 0 and read_ysize > 0:
                try:
                    sub = mntBand.ReadAsArray(read_xoff, read_yoff,
                                                read_xsize, read_ysize)
                    # Place into output array
                    mntArr[arr_yoff:arr_yoff + read_ysize,
                        arr_xoff:arr_xoff + read_xsize] = sub

                except Exception as e:
                    # Reading failed → keep nodata-filled array
                    print("ReadAsArray failed:", e)

            # Store final result
            self.mntArr = mntArr 
        
        mntDS = None

    def readMNTWithCoord(self,coordinate) : 

        if self.mntArr is None : return None

        xPixel = math.floor((coordinate[0] - self.mntGeo[0]) / self.mntGeo[1])
        yPixel = math.floor((coordinate[1] - self.mntGeo[3]) / self.mntGeo[5])
        
        pxRead = xPixel - self.pxStart 
        pyRead = yPixel - self.pyStart 
        
        rows, cols = self.mntArr.shape
        
        if 0 <= pxRead < cols and 0 <= pyRead < rows : return self.mntArr[pyRead,pxRead]
        
        else : return None
        

    def removeImportMNT(self) : 
        self.currentMNTPath = ""
        self.setStateMNT(False,self.currentMNTPath)

    def setStateMNT(self, enabled, label) :
        self.ui.radioButtonCut.setEnabled(enabled)
        self.ui.radioButtonDraw.setEnabled(enabled)
        self.ui.pushButtonRemoveMNT.setEnabled(enabled)
        self.ui.importLineMNT.setText(label)

    def closeEvent(self,event):
        self.closeWindow.emit()

    def loadParamFile(self):

        self.ParamDict = {}
        
        self.currentNoValidKey = []
        with open(self.JSONPath) as f : 
            self.ParamDict = json.load(f)
        
        info_raster = self.ParamDict['info_raster']
        stereoscope = self.ParamDict['stereoscope'] 

        if info_raster['image_dir'] : self.ui.importLineProject.setText(info_raster['image_dir'])
            
        if info_raster['mnt_file'] : 
            self.currentMNTPath = info_raster['mnt_file']
            self.ui.importLineMNT.setText(os.path.basename(self.currentMNTPath))
            self.ui.radioButtonCut.setEnabled(True)
            self.ui.radioButtonDraw.setEnabled(True)
            self.ui.pushButtonRemoveMNT.setEnabled(True)
        else : self.currentMNTPath = ''

        desktop = QtWidgets.QApplication.desktop()
        screenCount = desktop.screenCount()-1
        self.ui.spinBoxUpScreen.setMaximum(screenCount)
        self.ui.spinBoxDownScreen.setMaximum(screenCount)

        self.ui.spinBoxUpScreen.setValue(stereoscope['ecran_haut'])
        self.ui.spinBoxDownScreen.setValue(stereoscope['ecran_bas'])

        self.ui.checkBoxFlip.setChecked(stereoscope['miroir_OFF'])

        self.rehaussementParam = self.ParamDict['rehaussement']

    def saveParamFile(self) :

        self.ParamDict['stereoscope']['ecran_haut'] = self.ui.spinBoxUpScreen.value()
        self.ParamDict['stereoscope']['ecran_bas'] = self.ui.spinBoxDownScreen.value()
        self.ParamDict['stereoscope']['miroir_OFF'] = self.ui.checkBoxFlip.isChecked()

        self.ParamDict['info_raster']['image_dir'] = self.ui.importLineProject.text()
        self.ParamDict['info_raster']['mnt_file'] = self.currentMNTPath 
        self.ParamDict['info_raster']['user_image'] = self.ui.labelLeftName.text()

        self.ParamDict['rehaussement'] = self.rehaussementParam 

        with open(self.JSONPath,'w',encoding="utf-8") as f : 
            json.dump(self.ParamDict,f,indent=2,ensure_ascii=False)
        
    def actionShowScreenNumber(self) :

        if self.listGraphWinObj : self.closeScreenWindow()
        
        desktop = QtWidgets.QApplication.desktop()
        screenCount = desktop.screenCount()
        self.ui.spinBoxUpScreen.setMaximum(screenCount-1)
        self.ui.spinBoxDownScreen.setMaximum(screenCount-1)
        for i in range(screenCount) :

            screenGeo = desktop.screenGeometry(i)
            center = (int(screenGeo.width()/2), int(screenGeo.height()/2))
            #rect = QtCore.QRect(0,0,125,175)
            graphWin = graphicsWindow()
            graphWin.resize(125,175)
            #graphWin.ui.graphicsView.setGeometry(rect)
            graphWin.move(QtCore.QPoint(screenGeo.x()+center[0]-50,screenGeo.y()+center[1]-50))                
            
            
            scene = QtWidgets.QGraphicsScene()
            scene.setSceneRect(QtCore.QRectF(0,0,125,175))
            scene.addText(str(i),QtGui.QFont('Times',80)) 
            graphWin.ui.graphicsView.setScene(scene)
            
            graphWin.show()
            
            self.listGraphWinObj.append(graphWin)
        
        self.screenNumberTimer.start(6000)


    def closeScreenWindow(self) :
        self.screenNumberTimer.stop()
        for win in self.listGraphWinObj:
            win.close()
        self.listGraphWinObj.clear()

class graphicsWindow(QtWidgets.QMainWindow): 
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.ui = Ui_graphicsWindow()
        self.ui.setupUi(self)
